ops:
  shacl_simple:
    inputs:
      sgurl: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-df/code/notebooks/validation/shapes/oih_search.ttl
      shapes: {}
      source_emod: "emod"
      sources: {}
    config:
      sgurl: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-df/code/notebooks/validation/shapes/oih_search.ttl

